packages:
  - packages/*
  - app/examples/*
  - app/*

catalog:
  '@ai-sdk/anthropic': 2.0.6
  '@ai-sdk/groq': 2.0.14
  '@ai-sdk/openai': 2.0.20
  '@ai-sdk/google': 2.0.8
  '@ai-sdk/provider': 2.0.0
  '@ai-sdk/ui-utils': 1.2.11
  ai: 5.0.22
  uuid: 11.1.0
  zod: 4.0.16
  zod-to-json-schema: 3.24.3
  dotenv: 16.4.7
  '@types/bun': latest  
  typescript: 5.8.3
  tsup: 8.5.0
  vitest: 3.2.4
  chalk: 5.3.0
  '@vitest/ui': 3.2.4
  '@openrouter/ai-sdk-provider': 1.1.2


overrides:
  axiomkit: 'link:'
