packages:
  - packages/*
  - examples/*

catalog:
  '@ai-sdk/anthropic': 1.2.3
  '@ai-sdk/groq': 1.2.2
  '@ai-sdk/openai': 1.3.5
  '@ai-sdk/google': 1.2.17
  '@ai-sdk/provider': 1.1.0
  '@ai-sdk/ui-utils': 1.2.3
  typescript: 5.8.3
  ai: 4.3.17
  tsup: 8.3.6
  vitest: 3.2.4
  uuid: 11.1.0

overrides:
  axiom-kit: 'link:'
