packages:
  - packages/*
  - app/examples/*
  - app/*

catalog:
  '@ai-sdk/anthropic': 1.2.3
  '@ai-sdk/groq': 1.2.9
  '@ai-sdk/openai': 1.3.5
  '@ai-sdk/google': 1.2.17
  '@ai-sdk/provider': 1.1.0
  '@ai-sdk/ui-utils': 1.2.3
  ai: 4.3.19  # Setting AI
  uuid: 11.1.0
  zod: 3.25.23
  zod-to-json-schema: 3.24.3
  dotenv: 16.4.7
  '@types/bun': latest  
  typescript: 5.8.3
  tsup: 8.5.0
  vitest: 3.2.4
  chalk: 5.3.0
  '@vitest/ui': 3.2.4


overrides:
  axiomkit: 'link:'
